### PR TITLE
Changes in inventory and provisioning intent module and config verification in network settings and site intent module

### PR DESCRIPTION
**Pull request by madhansansel**
a) Introducing config_verify to verify the state operations in Catalyst Center in network settings and site intent module
b) Changes to support inventory and provisioning intent modules

### CODE REVIEW

**Comment by madhansansel** [comment]
@fmunozmiranda @wastorga, can you please review and approve the changes?

**Comment by madhansansel** [comment]
Hello @fmunozmiranda @wastorga, can you please review and approve the changes?

**Comment by madhansansel** [comment]
Hello @fmunozmiranda @jbogarin @wastorga @bvargasre, can you please review and approve the changes?

**Comment by fmunozmiranda** [comment]
@madhansansel please update version in galaxy file

**Comment by madhansansel** [comment]
Hello @fmunozmiranda, thanks for the kind review. I updated the version galaxy file. Could you please approve the request?

**Comment by madhansansel** [comment]
Hello @fmunozmiranda, thanks for the kind review. I updated the version galaxy file. Could you please approve the request?

**Pull request merged**
