### PR TITLE
Adding Intent modules for PnP usecase

### PR DESCRIPTION
**Pull request by madhansansel**
As part of PnP usecase, we implemented template_intent, site_intent, pnp_intent modules.

### CODE REVIEW

**Comment by bvargasre** [comment]
Hello team reviewing the pull request I saw that you need to add `template_intent`, `site_intent` and `pnp_intent` to the sanity, this is easy is to go to the tests/sanity/ignore-2.9 and ignore-2.10 files and add the three following the structure of the others for example:
`plugins/modules/pnp_intent.py compile-2.6!skip # Python 2.6 is not supported by the DNA Center SDK`
`plugins/modules/pnp_intent.py compile-2.7!skip # Python 2.7 is not supported by the DNA Center SDK`
For ignore-2.11 it is the same but adding an import
`plugins/modules/pnp_intent.py import-2.7 # Python 2.7 is not supported by the DNA Center SDK`

**Comment by wastorga** [comment]
Dear @madhansansel, our workflow found multiple errors.
You can see them by clicking 'Details' in the CI / Sanity (Ⓐdevel) row.

Most of them are related to pep8 and pylint.
```
ERROR: Found 363 pep8 issue(s) which need to be resolved:
...
ERROR: Found 90 pylint issue(s) which need to be resolved:
...
```

Some are related to shebang and are easy to fix
```
ERROR: Found 3 shebang issue(s) which need to be resolved:
ERROR: plugins/modules/pnp_intent.py:1:1: expected module shebang "b'#!/usr/bin/python'" but found: b'#!/usr/bin/env python'
ERROR: plugins/modules/site_intent.py:1:1: expected module shebang "b'#!/usr/bin/python'" but found: b'#!/usr/bin/env python'
ERROR: plugins/modules/template_intent.py:1:1: expected module shebang "b'#!/usr/bin/python'" but found: b'#!/usr/bin/env python'
```

Your plugin Ansible Modules do not seem to be allowed to import from ansible.errors

ERROR: Found 1 import issue(s) on python 3.9 which need to be resolved:
ERROR: plugins/modules/pnp_intent.py:640:0: traceback: ImportError: import of "ansible.errors" is not allowed in this context
See documentation for help: https://docs.ansible.com/ansible-core/devel/dev_guide/testing/sanity/import.html

You could try to capture the general `Exception` instead and remove the import.

We will take care of these ones.
```
ERROR: Found 4 import issue(s) on python 2.7 which need to be resolved:
ERROR: plugins/module_utils/dnac.py:274:12: traceback: SyntaxError: invalid syntax
ERROR: plugins/modules/pnp_intent.py:719:37: traceback: SyntaxError: invalid syntax
ERROR: plugins/modules/site_intent.py:365:37: traceback: SyntaxError: invalid syntax
ERROR: plugins/modules/template_intent.py:789:34: traceback: SyntaxError: invalid syntax

ERROR: Found 4 compile issue(s) on python 2.7 which need to be resolved:
ERROR: plugins/module_utils/dnac.py:274:12: SyntaxError: def exec(self, family, function, params=None, op_modifies=False, **kwargs):
ERROR: plugins/modules/pnp_intent.py:719:37: SyntaxError: response = self.dnac.exec(
ERROR: plugins/modules/site_intent.py:365:37: SyntaxError: response = self.dnac.exec(
ERROR: plugins/modules/template_intent.py:789:34: SyntaxError: items = self.dnac.exec(
```

Finally, there are some issues trying to render your documentation, please review them by executing 
```shell
$ ansible-doc -t module cisco.dnac.pnp_intent
$ ansible-doc -t module cisco.dnac.site_intent
$ ansible-doc -t module cisco.dnac.template_intent
```

I added my teammates to help you with the changes.

**Comment by wastorga** [comment]
@madhansansel

I think the easiest way to run the test locally is to create the folders `ansible_collections/cisco/dnac` and paste the contents of the dnacenter-ansible there. Maybe a hard link could work too, I am not sure, I have not tested it.

So you have something like this

Screen Shot 2022-08-10 at 11 59 37

With that setup you can run the following

```shell
$ # Run all sanity tests
$ ansible-test sanity

$ # Run all sanity tests against against certain files
$ ansible-test sanity plugins/modules/pnp_intent.py

$ # I recommend that you redirect both stdout and stderr to a file
$ # so the above command becomes something like this
$ ansible-test sanity plugins/modules/pnp_intent.py &> sanity.log
```

**Comment by wastorga** [comment]
I think we are near resolving the issues.

@madhansansel  @rishitachowdhary, please review the logs of the last check.
If you have any doubts feel free to ask them.

When you are done submitting changes, comment here so one of us (@fmunozmiranda , @bvargasre , @wastorga )  can approve the GitHub action to review your changes.

**Comment by rishitachowdhary** [comment]
[wastorga](https://github.com/wastorga) We have resolved most of the issues reported in the latest sanity check.

But we are unable to resolve the issues related to compile/import related to Python2.6/Python2.7.
We have added our files to the following ignore lists -  ignore-2.9.txt, ignore-2.10.txt and ignore-2.11.txt

Kindly help us in resolving these issues.

**Comment by wastorga** [comment]
@rishitachowdhary, great.

Of course, I am going to take a look at the issues related to compile/import related to Python2.6/Python2.7.

**Comment by wastorga** [comment]
I created a branch to see what changes were needed on the ignore sanity files.

**Comment by wastorga** [comment]
@madhansansel, @rishitachowdhary 
Sorry, I forgot that Github does not have the ability to reopen pull request.

Could you create a new pull request?

I am attaching a compressed file with the needed changes for the `tests/sanity` ignore files.
[sanity.zip](https://github.com/cisco-en-programmability/dnacenter-ansible/files/9550632/sanity.zip)

Thanks.

**Pull request merged**
