### PR TITLE
Adding new intent modules for inventory, discovery and device credentials

### PR DESCRIPTION
**Pull request by madhansansel**
Problem Description:
a) New inventory intent module that is used to perform over devices which includes Adding, Deleting, Resyncing, Updating Device details etc. for all types of devices - Network Device, Compute Device, Meraki Device, Firepower Management System Device and Third Party Devices.

b) New device credential inventory module that is used to Create, Update and Delete Global Device Credentials and Assign Credentials to a sites

c) New discovery inventory module that is used to discover the devices.

d) Minor changes to other files.

Documentation: 
Documentation is done as part of the code

Sanities:
Run sanities successfully

### CODE REVIEW

**Comment by madhansansel** [comment]
@wastorga , @fmunozmiranda, @racampos, @bvargasre can you please review the changes and approve?

**Comment by fmunozmiranda** [comment]
Hi @madhansansel  could you please update the CHANGELOG with your changes, thank you.

**Comment by madhansansel** [comment]
Hi @fmunozmiranda, updated the changelogs. Could you please review and approve the PR? Thank you very much!

**Comment by fmunozmiranda** [comment]
@madhansansel Could you please change version to 6.8.0? New modules and plugins should increase the minor number (remembering the MAJOR.MINOR.PATCH versioning).

Please change property `version_added` from `6.7.0` to `6.8.0`?

Thanks.

**Comment by madhansansel** [comment]
@fmunozmiranda, updated the change version to 6.8.0 as requested. Could you please review and approve the PR? Thank you very much!

**Comment by fmunozmiranda** [comment]
New modules have this property: https://github.com/cisco-en-programmability/dnacenter-ansible/blob/67a67f8fbbc65f3ad3368782a30592868a9e2c7f/plugins/modules/device_credential_intent.py#L22C23-L22C23

Please change it from 6.7.0 to 6.8.0

**Comment by madhansansel** [comment]
@fmunozmiranda  Changed the version from  6.7.0 to 6.8.0 in device_credential_intent and inventory_intent modules. Could you please review and approve the PR? Thank you very much!

**Pull request merged**
