### PR TITLE
Documentation changes in the Site example

### PR DESCRIPTION
**Pull request by madhansansel**
Problem Description:
The site example needs to have config as list but example gives as dict which causes confusion in usages and needs fixing. #105

Fix:
Change the config as list from dictionary.

### CODE REVIEW

**Comment by madhansansel** [comment]
@racampos and @jbogarin can you please approve the changeset?

**Comment by madhansansel** [comment]
@racampos and @jbogarin can you please approve the changeset?

**Comment by wastorga** [comment]
Hi, @madhansansel . 

plugins/modules/network_intent has 27 doc related issues, please review and solve them.

https://github.com/cisco-en-programmability/dnacenter-ansible/actions/runs/5377436582/jobs/9787352038?pr=107

**Comment by madhansansel** [comment]
We wanted to commit only the first commit in main line https://github.com/cisco-en-programmability/dnacenter-ansible/pull/107/commits/4fc083550a7ad006e770e6ec4d3009f9af686389. and not the other two changes related to network_intent modules.

**Comment by wastorga** [comment]
@madhansansel  I added the commit in the develop branch.

@fmunozmiranda has some fixes he needs to make and publish to the collection. 
He will be releasing a new version later today.

**Comment by madhansansel** [comment]
@wastorga , Could you please remove 
[network intent playbook](https://github.com/cisco-en-programmability/dnacenter-ansible/pull/107/commits/7cd74aff57e1281300f767e1a1d921b07247ac8a) 
and 
[network intent module](https://github.com/cisco-en-programmability/dnacenter-ansible/pull/107/commits/16d333019ecf748095f4ddd1f3453bb94bd6f489)? 

We wanted to publish only 
[Documentation changes in the example](https://github.com/cisco-en-programmability/dnacenter-ansible/pull/107/commits/4fc083550a7ad006e770e6ec4d3009f9af686389).

**Comment by wastorga** [comment]
@madhansansel  I added the commit in the develop branch directly. So we could create another pull request to avoid adding the other files you were working on.

@fmunozmiranda already created another pull request with the changes in plugins/modules/site_intent.py

You can verify it here https://github.com/cisco-en-programmability/dnacenter-ansible/pull/108/commits/996ce7e14fc5a23a38bba69e14ecdfe0a2239c87

**Comment by wastorga** [comment]
Once it's published, we will update you here and close this pull request.
Feel free to open another one until you want to merge your new commits.

**Comment by wastorga** [comment]
For the next pull requests, I will strongly encourage that:
1. You work in a separate branch, i.e., your own development branch on madhansansel/dnacenter-ansible
2. You push the changes of that branch when they are ready to your main branch on madhansansel/dnacenter-ansible
3. You then request to merge the changes of madhansansel/dnacenter-ansible:main to cisco-en-programmability:**develop**.

**Comment by wastorga** [comment]
I thought by your other commits that you still needed to finish until you commented saying otherwise.
So for future changes, let's follow the previous advice.

**Comment by madhansansel** [comment]
@wastorga Sure, we will merge the changes from madhansansel/dnacenter-ansible:main to cisco-en-programmability:develop in our next commits. Thank you very much. We can close this

**Comment by wastorga** [comment]
@madhansansel. No problem! And thank you. Version 6.7.3 has been released 3 minutes ago.
https://galaxy.ansible.com/cisco/dnac

**Pull request closed without merging**
