### PR TITLE
Adding intent modules template_intent, site_intent, pnp_intent, swim_intent for pnp usecase

### PR DESCRIPTION
**Pull request by madhansansel**
As suggested, create a new pull request and updated the sanity files.

### CODE REVIEW

**Review by madhansansel — COMMENTED** [review]
Added intent modules template_intent, site_intent, pnp_intent, swim_intent modules as part  pnp usecase. All the sanities got passed now.

**Comment by wastorga** [comment]
Looks good, @madhansansel, thanks.
We need to update the documentation and version of the collection to upload the new version to Galaxy.
I'll keep you updated.

**Comment by madhansansel** [comment]
Hi William,

Could you please let us know the steps to do documentation and upload to Galaxy?

Thanks,
Madhan

From: William Astorga ***@***.***>
Reply to: cisco-en-programmability/dnacenter-ansible ***@***.***>
Date: Tuesday, 13 September 2022 at 5:33 AM
To: cisco-en-programmability/dnacenter-ansible ***@***.***>
Cc: Madhan Sankaranarayanan ***@***.***>, Mention ***@***.***>
Subject: Re: [cisco-en-programmability/dnacenter-ansible] Adding intent modules template_intent, site_intent, pnp_intent, swim_intent for pnp usecase (PR #76)


Looks good, @madhansansel<https://github.com/madhansansel>, thanks.
We need to update the documentation and version of the collection to upload the new version to Galaxy.
I'll keep you updated.

**Comment by wastorga** [comment]
Hi, @madhansansel 

They are the following:

1. Add a new entry in changelogs/changelog.yaml. 
Version changes are usually minor or patches. So that when a new minor Ansible version comes along, Ansible team are able to include our new version in that Ansible's collections.
2. Update the Compatibility matrix on README.md
3. Update the version on galaxy.yml
4. Update the version_added of each module documentation or option/parameter as necessary.

For this merge you can see them with more detail at 4112779c12a645acc87dd8c0a2c61f7eb89070c7

For the publishing part, I'll talk with you by DM.

**Pull request merged**
