### PR TITLE
Changes in workflow manager modules

### PR DESCRIPTION
**Pull request by madhansansel**
## Description
Changes in workflow manager modules

- Changes in circleci to run test cases in integration branch
- Added support for bulk operations on multiple access points in accesspoint_workflow_manager
- Bug fixes in inventory_workflow_manager
- Enhancements in sda_fabric_devices_workflow_manager.py to support route distribution protocol
- Enhancements in sda_fabric_sites_zones_workflow_manager.py
- Bug fixes in sda_fabric_virtual_networks_workflow_manager.py
- Changes in site_workflow_manager
- accesspoint_workflow_manager - added attribute bulk_update_aps
- sda_fabric_devices_workflow_manager.py - added attribute route_distribution_protocol
- sda_fabric_sites_zones_workflow_manager.py - added attribute site_name_hierarchy and removed attribute site_name

## Type of Change
- [YES] Bug fix
- [NO ] New feature
- [YES ] Breaking change
- [YES] Documentation update

## Checklist
- [YES ] My code follows the style guidelines of this project
- [YES] I have performed a self-review of my own code
- [YES ] I have commented my code, particularly in hard-to-understand areas
- [YES] I have made corresponding changes to the documentation
- [YES] My changes generate no new warnings
- [YES] I have added tests that prove my fix is effective or that my feature works
- [YES] New and existing unit tests pass locally with my changes
- [YES] Any dependent changes have been merged and published in downstream modules
- [YES] All the sanity checks have been completed and the sanity test cases have been executed

## Ansible Best Practices
- [YES] Tasks are idempotent (can be run multiple times without changing state)
- [YES] Variables and secrets are handled securely (e.g., using `ansible-vault` or environment variables)
- [YES] Playbooks are modular and reusable
- [YES] Handlers are used for actions that need to run on change

## Documentation
- [YES] All options and parameters are documented clearly.
- [YES]Examples are provided and tested.
- [YES] Notes and limitations are clearly stated.

### CODE REVIEW

**Comment by JosePabloOcampo1212** [comment]
Hello, I wanted to let you know that some errors are occurring.

The first one is in “plugins/action/event_subscription.py” the error indicates that the variable tmp_result is being used before being assigned a value in the event_subscription.py file on line 111. To resolve this problem, make sure that tmp_result is initialized correctly before trying to use it.

The second error indicates that there are options in the discovery.py file that are duplicated. This is in the plugins/modules/discovery.py directory.

It is failing in sanity.

**Comment by madhansansel** [comment]
> Hello, I wanted to let you know that some errors are occurring.
> 
> The first one is in “plugins/action/event_subscription.py” the error indicates that the variable tmp_result is being used before being assigned a value in the event_subscription.py file on line 111. To resolve this problem, make sure that tmp_result is initialized correctly before trying to use it.
> 
> The second error indicates that there are options in the discovery.py file that are duplicated. This is in the plugins/modules/discovery.py directory.
> 
> It is failing in sanity.

**Comment by madhansansel** [comment]
Hello @JosePabloOcampo1212 , the sanity errors are not related to our workflow manager modules. Can you please help in merging our workflow manager modules?

**Comment by JosePabloOcampo1212** [comment]
Hello, how are you?

Sorry for the delay, I was seeing that it is giving an error in these modules of yours plugins/modules/inventory_intent.py:1262 and in plugins/modules/inventory_workflow_manager.py:1268.

Could you check them?

Captura de pantalla 2024-11-12 a las 4 41 19 p  m

**Comment by madhansansel** [comment]
Hello @JosePabloOcampo1212, I am doing very good. Thank you. Hope you are doing great. We have resolved the sanity issues in this PR. Can you please check and approve the request?

**Pull request merged**
